// ============================================================
//  items/items_recipes.js - 所有料理配方
// ============================================================

Object.assign(ITEM_TEMPLATES, {

    // ========== 腿部料理 ==========
    aisha_leg_steak: { id: "aisha_leg_steak", name: "监工炭火烤腿", type: "consumable", desc: "由艾莎的腿制作而成的炭火烤腿，表皮呈焦黑色，淡金色的汗毛被燎得卷曲，切开后肉汁混着血水流出来，里面的肌肉还是粉红的，断面的大腿骨烤成了褐色，骨髓凝固成乳白色，散发着硫磺与烤肉混合的粗犷香气，腿根处的细毛被血染湿，贴在紧致的皮肤上。", effect: "maxHp", value: 10, ingredients: ["艾莎的腿","油","盐"], seasonings: ["oil","salt"], cookStory: ["你用手指插进腿根的断口，将粗盐抹在温热的肌肉缝里，淡金色的汗毛在血迹映衬下格外明显，断面露出的大腿骨白森森的，你用力揉搓让盐粒渗进肌肉纤维；","你用铁签穿过脚踝，架在煤炉上，炭火烧到暗红，油脂滴下去发出滋滋的声响，每隔五分钟刷一层油，蜜色的皮肤贴上滚烫的铁条；","你翻转着腿部，继续刷油烤制了二十分钟，直到表皮呈现焦黑色，断面的大腿骨烤成褐色，骨髓凝固。","料理已完成！获得了\u201c监工炭火烤腿\u201d"] },
    liana_leg_steak: { id: "liana_leg_steak", name: "骑士剑串烤腿", type: "consumable", desc: "由莉娅娜的腿制作而成的剑串烤腿，表皮金黄酥脆，她常用的大剑贯穿其中，断面露出粗大的腿骨与发达的粉红肌肉，大腿内侧的淡金色汗毛被炭火烤得卷曲，贴在腿根，散发着黄油的奶香与迷迭香的草本气息混合着血腥与战场汗液的腥臊气息。", effect: "atk", value: 2, ingredients: ["莉娅娜的腿","迷迭香","骑士大剑"], seasonings: ["rosemary","knight_greatsword"], returnAfterCook: ["knight_greatsword"], cookStory: ["你将那条修长强健的腿用她自己的长剑从断面穿刺，剑身穿过大腿，剑尖从小腿内侧穿出，断面露出粗大的腿骨与发达的粉红肌肉，你涂抹黄油，让油脂渗入肌肉纤维，撒上迷迭香碎；","你将剑架在烤架上，炭火烤制，油脂滴落在板甲上发出滋滋声，大腿内侧细嫩的皮肉慢慢收紧；","你不断转动长剑，让腿部均匀受热，直到表皮呈现金黄酥脆的色泽，淡金色的汗毛被燎得卷曲。","料理已完成！获得了\u201c骑士剑串烤腿\u201d"] },
    cecilia_leg_steak: { id: "cecilia_leg_steak", name: "千金白丝炖腿", type: "consumable", desc: "由塞西莉亚的腿制作而成的白丝炖腿，白色厚丝袜紧紧包裹着娇小纤细的腿，被牛奶炖得半透明湿润，呈现出温润的乳白色，大腿根部干净白嫩，小腿细直，断面的细小腿骨与柔软的粉红肌肉浸在浓稠的奶液里，散发着香草与牛奶的甜香混合着白色丝袜纤维特有的气息。", effect: "agi", value: 2, ingredients: ["塞西莉亚的腿","牛奶","香草荚"], seasonings: ["milk","vanilla_bean"], cookStory: ["你提起那条娇小纤细的腿，白色厚丝袜还完好地包裹着纤细的大腿，丝袜被鲜血浸透后紧紧贴在皮肤上呈现出淡粉色，你将腿放入陶锅；","倒入牛奶和剖开的香草荚，牛奶淹没大腿，白色丝袜在奶液里慢慢被浸透，大腿根部干净白嫩的肌肤在奶液里若隐若现，断面的细小腿骨露出柔软的粉红肌肉；","你用小火将这条腿慢炖四十分钟，牛奶变得浓稠，丝袜的纤维与奶液融合，散发出甜香。","料理已完成！获得了\u201c千金白丝炖腿\u201d"] },
    isabella_leg_steak: { id: "isabella_leg_steak", name: "贵妇黑丝炖腿", type: "consumable", desc: "由伊莎贝拉的腿制作而成的黑丝炖腿，黑色丝袜紧紧包裹着修长丰满的腿，被牛奶炖得半透明湿润，呈现出妖艳的红黑色，大腿饱满圆润，小腿线条流畅充满弹性，断面露出的粗壮腿骨与丰厚的粉红肌肉浸在浓稠的奶液里，散发着香草与牛奶的甜香混合着黑色丝袜与伊莎贝拉丰满肉腿的浓烈肉香的混合气息。", effect: "maxHp", value: 15, ingredients: ["伊莎贝拉的腿","牛奶","香草荚"], seasonings: ["milk","vanilla_bean"], cookStory: ["你提起那条修长丰满的腿，黑色丝袜被鲜血浸透后紧紧贴在皮肤上，勾勒出饱满圆润的大腿曲线，你将腿放入大陶锅；","你倒入牛奶淹没大腿，加入剖开的香草荚，黑色丝袜在奶液里慢慢被浸透，大腿根部丰满的肌肤在奶液里若隐若现，断面露出粗壮的腿骨与丰厚的粉红肌肉；","你用小火慢炖了一小时，牛奶变得浓稠，黑色丝袜的纤维与奶液融合，散发出甜香。","料理已完成！获得了\u201c贵妇黑丝炖腿\u201d"] },
    sophie_leg_steak: { id: "sophie_leg_steak", name: "女仆凉拌腿肉", type: "consumable", desc: "由索菲的腿制作而成的凉拌腿肉，切片摆放在翠绿的生菜上，膝盖处老茧硬化成深褐色的切片与大腿内侧病态粉白的细嫩肉片形成强烈的颜色对比，皮肤半干半湿透着柠檬汁的清香，断面露出细小的股骨与粉白的肌肉组织，散发着柠檬汁的酸爽混合着橄榄油的清香与风干肉的韧劲。", effect: "def", value: 2, ingredients: ["索菲的腿","柠檬汁","盐","橄榄油","生菜"], seasonings: ["lemon_juice","salt","olive_oil","lettuce"], cookStory: ["你将那条苍白的细腿平放，膝盖处的老茧与色素沉着清晰可见，大腿内侧异常白皙细嫩，你用粗盐分别涂抹两个部位，腌制三日；","你将腿悬挂在阴凉处半风干，直到皮肤半干半湿，膝盖老茧硬化，大腿保持细嫩；","你将风干好的腿肉切片摆盘，膝盖部位深色老茧切片与大腿内侧粉白细肉交错摆放，淋上柠檬汁和橄榄油，配以生菜垫底。","料理已完成！获得了\u201c女仆凉拌腿肉\u201d"] },
    elena_leg_steak: { id: "elena_leg_steak", name: "艾莲娜腿排", type: "consumable", desc: "用艾莲娜的腿烹制的料理，优雅而精致。食用后可永久提升攻击力。", effect: "atk", value: 3, ingredients: ["莉娅娜的脚","盐","姜片"], seasonings: ["salt","ginger"], cookStory: ["你将艾莲娜的腿放在炉灶上...","教师的优雅双腿在火焰中起舞...","【占位符：艾莲娜腿排烹饪剧情】","料理完成了，充满知性的味道。"] },
    serena_leg_steak: { id: "serena_leg_steak", name: "瑟蕾娜腿排", type: "consumable", desc: "用瑟蕾娜的腿烹制的料理，蕴含着魔力。食用后可永久提升所有属性。", effect: "all", value: 5, ingredients: ["莉娅娜的乳房","莉娅娜的鲜奶","蜂蜜","吉利丁片"], seasonings: ["liana_milk","honey","gelatin_sheet"], cookStory: ["你将瑟蕾娜的腿放在炉灶上...","法师的腿部散发着魔力波动...","【占位符：瑟蕾娜腿排烹饪剧情】","料理完成了，魔力充盈。"] },

    // ========== 头部料理 ==========
    aisha_head_dish: { id: "aisha_head_dish", name: "监工碧眼浓汤", type: "consumable", desc: "由艾莎的头颅制作而成的碧眼浓汤，已经失去了脸颊的基本形状。汤色呈乳白色，两颗碧绿的眼珠变得乳白浑浊，像两颗煮老的鹌鹑蛋浮在汤面，嘴唇煮得发烂，露出煮成白色的牙龈，热气带着甜腥味往上飘，断面的颈椎骨露出苍白的截面，散发着矿井深处特有的潮湿与血腥混合的气息。", effect: "maxHp", value: 10, ingredients: ["艾莎的头颅","水","薄荷"], seasonings: ["water","mint"], cookStory: ["你将艾莎的头颅按进铁锅，水面刚好没过眉毛，手指插进她的短发里搓洗，扯掉结块的煤灰，血沫子浮上来，断面的粉红色气管与深红颈椎骨清晰可见，碧绿色的瞳孔在水里半睁着；","你点上火，水开后转小火，炖四十分钟，期间用勺子不断撇去浮沫，直到嘴唇在水里慢慢张开，露出牙龈，气管口冒出细小的气泡，碧绿色的瞳孔逐渐变得浑浊；","你加入薄荷，又炖了十分钟，让薄荷的清凉渗入头骨与面部肌肉。","料理已完成！获得了\u201c监工碧眼浓汤\u201d"] },
    liana_head_dish: { id: "liana_head_dish", name: "骑士红酒炖首", type: "consumable", desc: "由莉娅娜的头颅制作而成的红酒炖首，已经没有脸的基本形状。栗色长发在红酒里漂浮如海藻，红色瞳孔被酒液泡得略微浑浊，不再锐利，薄唇染成酒红色彻底煮烂，微微张开，脖颈断面的粗壮的颈动脉管腔里灌满了暗红色的酒液，散发着红酒的醇香混合着肉香与战场汗液的浓烈气息。", effect: "atk", value: 2, ingredients: ["莉娅娜的头颅","红酒","迷迭香"], seasonings: ["red_wine","rosemary"], cookStory: ["你摘下那颗头颅上戴着的头盔，解开栗色长发的高马尾，让湿漉漉的发丝散开在案板上，手指插进头发里梳理，扯掉凝固的血块，红色瞳孔在灯光下还半睁着，映出冷厉的光；","你将头颅放进陶罐，倒入红酒直至淹没下巴，酒液渗进断面的颈动脉管腔，染成更深的暗红，加入迷迭香，小火慢炖两小时；","你不断用勺子舀起红酒浇淋她的脸颊，让酒香渗入头骨，薄唇在酒液里微微张开，露出烂熟的舌尖。","料理已完成！获得了\u201c骑士红酒炖首\u201d"] },
    cecilia_head_dish: { id: "cecilia_head_dish", name: "千金蜜糖渍首", type: "consumable", desc: "由塞西莉亚的头颅制作而成的蜜糖渍首，乌黑亮丽的长发在琥珀色蜂蜜里如瀑布般缠绕漂浮，苍白细腻的脸颊泛着蜜糖的光泽，大而圆润的黑色眼睛像两颗浸泡在蜜液里的黑珍珠，睫毛又长又翘沾着蜜滴，粉嫩薄薄的嘴唇微张露出一点舌尖，脖颈断面的细小血管凝固成暗红色的蜜渍，散发着玫瑰与蜂蜜的甜香混合着十八岁少女特有的稚嫩体香。", effect: "agi", value: 2, ingredients: ["塞西莉亚的头颅","蜂蜜","玫瑰花瓣"], seasonings: ["honey","rose_petal"], cookStory: ["你捧起那颗精致娇小的头颅，解开乌黑长发的丝带，让发丝散开在瓷盘里，手指梳理头发，扯掉凝固的血块，苍白细腻的脸颊还带着稚气，大而圆润的黑色眼睛半睁着；","你将头颅放入蜜罐，蜂蜜淹没至头顶，少女头颅的乌黑长发在琥珀色蜜液里漂浮如瀑布，粉嫩薄薄的嘴唇微张，蜜液渗进断面的细小颈骨；","你撒上玫瑰花瓣，将罐子密封腌渍了三日，让蜜液充分渗入头骨，眼睛被蜜液泡得更加圆润湿润。","料理已完成！获得了\u201c千金蜜糖渍首\u201d"] },
    isabella_head_dish: { id: "isabella_head_dish", name: "贵妇金发浓汤", type: "consumable", desc: "由伊莎贝拉的头颅制作而成的金发浓汤，汤色呈浓稠的乳白色，金色波浪长发漂浮在汤面如熔化的蜂蜜，蓝色瞳孔被奶油泡得略微浑浊，丰满红润的嘴唇微张露出湿润的舌尖，脖颈断面的血管凝固成暗红色的奶油渍，散发着白葡萄酒的醇香混合着浓烈香水与成熟女性体香的气息。", effect: "maxHp", value: 15, ingredients: ["伊莎贝拉的头颅","奶油","白葡萄酒","肉豆蔻粉"], seasonings: ["cream","white_wine","nutmeg"], cookStory: ["你捧起那颗充满成熟诱惑的头颅，解开金色波浪长发，让发丝散开在汤锅里，手指梳理头发，扯掉凝固的血块，丰满红润的嘴唇还微张着，露出湿润的舌尖，蓝色瞳孔半睁着；","你倒入白葡萄酒淹没至头颅的眉骨，加入奶油和肉豆蔻粉，大火烧开后转小火慢炖，金色长发在奶白色的汤液里翻滚如熔化的蜂蜜；","你不断用勺子舀起汤汁浇淋她的脸颊，让奶油渗入头皮，炖煮一小时直到汤汁浓稠，头颅在汤里轻轻晃动。","料理已完成！获得了\u201c贵妇金发浓汤\u201d"] },
    sophie_head_dish: { id: "sophie_head_dish", name: "女仆果木熏首", type: "consumable", desc: "由索菲的头颅制作而成的果木烟熏首，亚麻色长发干枯如稻草般缠绕在头颅周围却带着苹果木的清香，皮肤呈现出病态的粉白色且紧绷干裂，本苍白的眼珠已萎缩凹陷在眼窝里，苍白单薄的嘴唇干裂微张露出细小的牙齿，脖颈断面的纤细颈椎骨露出苍白的截面，散发着苹果木的清香混合着迷迭香的草本气息。", effect: "def", value: 2, ingredients: ["索菲的头颅","苹果木屑","盐","迷迭香"], seasonings: ["apple_wood_chips","salt","rosemary"], cookStory: ["你将索菲那颗清瘦的头颅提起，亚麻色长发干枯毛躁如稻草，你用清水冲洗头发，扯掉凝固的血块，苍白单薄的脸颊还带着驯服的神情，浅灰色瞳孔半睁着露出眼底；","你将头颅悬挂在通风处，用粗盐涂抹断面和脖颈，撒上迷迭香碎，让盐粒渗入纤细的颈椎；","你用苹果木屑将头颅冷烟熏制七日，直到头皮紧绷如鼓皮，头发吸附木香的清甜，嘴唇干裂发白却透着淡淡的果香。","料理已完成！获得了\u201c女仆果木熏首\u201d"] },
    elena_head_dish: { id: "elena_head_dish", name: "教师银丝清汤", type: "consumable", desc: "由艾莲娜的头颅制作而成的银丝清汤，汤色清亮透明，银色长卷发漂浮在汤面如瀑布般泛着冷冽光泽，青色瞳孔被汤汁泡得略微浑浊却依然冷艳，苍白如瓷的脸颊透着温润，薄唇微抿，脖颈断面的颈椎骨露出苍白的截面，散发着雪莉酒的醇香混合着清鸡汤的鲜美。", effect: "atk", value: 3, ingredients: ["艾莲娜的头颅","雪莉酒","鸡肉"], seasonings: ["sherry","chicken"], cookStory: ["你将那颗冷艳高贵的头颅捧起，银色长卷发如瀑布般散开，手指梳理发丝，扯掉凝固的血块，青色瞳孔半睁着映着冷光，你用鸡肉熬成的鸡汤冲洗苍白如瓷的脸颊；","你将头颅放入砂锅，倒入清鸡汤淹没至眉骨，加入雪莉酒，小火慢炖三小时，让酒香渗入头骨，银色长发在汤里翻滚如丝；","你不断舀起汤汁浇淋她的额头，直到头皮紧绷，薄唇微抿，汤面浮着一层清亮的油花。","料理已完成！获得了\u201c教师银丝清汤\u201d"] },
    serena_head_dish: { id: "serena_head_dish", name: "瑟蕾娜头料理", type: "consumable", desc: "【占位符：瑟蕾娜头部料理描述】", effect: "all", value: 5, ingredients: ["莉娅娜的脚","盐","姜片"], seasonings: ["salt","ginger"], cookStory: ["【占位符：头部料理烹饪剧情】"] },

    // ========== 躯干料理 ==========
    aisha_torso_dish: { id: "aisha_torso_dish", name: "监工血肉拼盘", type: "consumable", desc: "由艾莎的躯干制作而成的血肉拼盘，臀肉呈深红色，肌肉纤维致密，表面泛着血光，腹肌切块摆在周围像粉红色的砖块，中央的那团血肉还在渗出血水，阴毛粘在上面，穴口微张，散发着一股混杂着汗水与原始体味的浓烈野性腥甜，整体呈现出一种充满力量的野性美感。", effect: "maxHp", value: 20, ingredients: ["艾莎的躯干","盐"], seasonings: ["salt"], cookStory: ["你将躯干翻过来，屁股朝上，用刀沿着臀沟划下去，切下最肥美的臀尖肉，露出里面粉红的肉和白色的脂肪层，肌肉紧实回弹有力；","你挖出一团阴部的血肉，放在盘子中央，那地方还张着，阴毛乱糟糟的；","你撒上矿盐，用手指抹匀，让血水慢慢渗出来，腹肌切块摆在周围，臀肉呈扇形摆放。","料理已完成！获得了\u201c监工血肉拼盘\u201d"] },
    liana_torso_dish: { id: "liana_torso_dish", name: "骑士马鞭蒸躯", type: "consumable", desc: "由莉娅娜的躯干与骑士战马的阴茎制作而成的马鞭蒸躯，骑士与她最爱的战马终于紧密地融合在了一起。骑士腰肢紧实有力，小腹平坦腹肌线条清晰，浓密的深红色阴毛覆盖着被撑开的暗红色阴道口，马阴茎的粉白海绵体插在阴道中，顶端露出宫颈口，散发着马腥与女性淫液混合的浓烈气息。", effect: "atk", value: 3, ingredients: ["莉娅娜的躯干","骑士战马的阴茎","姜片","葱"], seasonings: ["warhorse_penis","ginger","scallion"], cookStory: ["你将骑士战马那根粗大的马阴茎剥去外皮，露出粉白的海绵体，掰开莉娅娜紧闭的阴道口，将马阴茎用力深深插入，直到骑士的阴道完全将这根巨大的阴茎吞没；","你将插入马鞭的躯干放入蒸锅，马阴茎的根部卡在阴道口，姜片和葱段铺在周围，大火蒸制，蒸汽中马阴茎在阴道内膨胀，与子宫内壁贴合；","蒸一个小时后打开锅盖，马阴茎与阴道内壁粘连，抽出时带出透明的黏液，阴道口呈现被撑开后的暗红色。","料理已完成！获得了\u201c骑士马鞭蒸躯\u201d"] },
    cecilia_torso_dish: { id: "cecilia_torso_dish", name: "千金酿奶蒸躯", type: "consumable", desc: "由塞西莉亚的躯干制作而成的酿奶蒸躯，腰肢极细小腹平坦光滑，处女阴部的浅粉色阴唇微张，从狭窄的阴道口里流出塞西莉亚自己的乳白色奶液，肛门处溢出玫瑰色的酱汁与透明黏液混合，紧致狭窄的肛口呈现被撑开后的浅粉色褶皱细密整齐，如同一朵樱花，散发着蜂蜜与玫瑰的甜香混合着处女阴部特有的稚嫩腥甜气息。", effect: "agi", value: 3, ingredients: ["塞西莉亚的躯干","塞西莉亚的奶","蜂蜜","玫瑰花瓣"], seasonings: ["cecilia_milk","honey","rose_petal"], cookStory: ["你将那娇小而纤细的躯干平放，掰开处女紧闭的浅粉色阴唇，将塞西莉亚的新鲜奶液与蜂蜜混合，用细管注入阴道深处，又将捣碎的玫瑰花酱填入清洗后的肛门；","你将躯干放入蒸锅，奶液在处女阴道里受热蒸发，玫瑰花酱在肛门里深入皮肤，与残留的透明黏液混合；","你将塞西莉亚的躯干蒸制二十分钟，躯干的阴道口流出滚烫的奶液，肛门处溢出玫瑰色的酱汁。","料理已完成！获得了\u201c千金酿奶蒸躯\u201d"] },
    isabella_torso_dish: { id: "isabella_torso_dish", name: "贵妇精液酿躯", type: "consumable", desc: "由伊莎贝拉的躯干、乳汁与骑士战马的精液制作而成的精液酿躯。", effect: "maxHp", value: 25, ingredients: ["伊莎贝拉的躯干","伊莎贝拉的奶","骑士战马精液","红枣"], seasonings: ["isabella_milk","knight_semen","red_date"], cookStory: ["你将那丰满的躯干平放，将精液与奶液混合注入阴道深处，再将剩余的精奶混合物填入肛门；","你将躯干放入蒸锅蒸制，阴道口和肛门处溢出凝固的奶白色粘稠汁液，丰满的臀部被蒸得泛红；","你将躯干蒸好后取出。","料理已完成！获得了\u201c贵妇精液酿躯\u201d"] },
    sophie_torso_dish: { id: "sophie_torso_dish", name: "女仆香草腌躯", type: "consumable", desc: "由索菲的躯干制作而成的香草腌躯。", effect: "def", value: 3, ingredients: ["索菲的躯干","盐","香草荚","月桂叶","橄榄油"], seasonings: ["salt","vanilla_bean","bay_leaf","olive_oil"], cookStory: ["你将那瘦弱的躯干平放，用橄榄油涂抹全身；","你用粗盐、百里香和月桂叶涂抹躯干全身，腌制十五日；","你将躯干悬挂风干，直到皮肉紧缩，透着香草的气息。","料理已完成！获得了\u201c女仆香草腌躯\u201d"] },
    elena_torso_dish: { id: "elena_torso_dish", name: "教师冷玉刺身", type: "consumable", desc: "由艾莲娜的躯干制作而成的冷玉刺身，切片薄如蝉翼摆放在翠绿的紫苏叶上，散发着山葵的辛辣混合着酱油的咸鲜与艾莲娜的特有气息。", effect: "atk", value: 4, ingredients: ["艾莲娜的躯干","山葵酱","酱油","紫苏叶"], seasonings: ["wasabi_paste","soy_sauce","perilla_leaf"], cookStory: ["你将那白皙匀称的躯干平放，用薄刃沿着腰肢修长紧致的线条切下薄片；","你将切好的肉片摆放在紫苏叶上，淋上酱油，涂抹山葵酱在断面；","你将躯干摆成侧卧姿态。","料理已完成！获得了\u201c教师冷玉刺身\u201d"] },
    serena_torso_dish: { id: "serena_torso_dish", name: "瑟蕾娜躯干料理", type: "consumable", desc: "【占位符：瑟蕾娜躯干料理描述】", effect: "all", value: 8, ingredients: ["瑟蕾娜的躯干","【占位符：辅料1】","【占位符：辅料2】"], seasonings: ["ingredient_1","ingredient_2"], cookStory: ["【占位符：躯干料理烹饪剧情】"] },

    // ========== 手臂料理 ==========
    aisha_arm_dish: { id: "aisha_arm_dish", name: "监工葱香炖臂", type: "consumable", desc: "由艾莎的右臂制作而成的葱香炖臂，汤色乳白，肌肉纤维清晰可见，散发着浓郁的肉香混着野葱的清香。", effect: "atk", value: 2, ingredients: ["艾莎的手臂","水","盐","葱"], seasonings: ["water","salt","scallion"], cookStory: ["你用菜刀把手臂剁成三段，骨头砸在锅底咚咚响，加水没过，大火烧开撇去血沫；","你加入野葱和粗盐，转小火慢炖两小时，肌肉纤维在汤里慢慢散开；","你关火焖了十分钟，让骨肉充分分离，汤汁变得乳白。","料理已完成！获得了\u201c监工葱香炖臂\u201d"] },
    liana_arm_dish: { id: "liana_arm_dish", name: "骑士肌纹烤臂", type: "consumable", desc: "由莉娅娜的右臂制作而成的肌纹烤臂，蜜色的皮肤焦黄油亮，散发着黑胡椒的辛辣混合着烤肉香与战场汗液的腥臊气息。", effect: "atk", value: 3, ingredients: ["莉娅娜的手臂","黑胡椒","橄榄油"], seasonings: ["black_pepper","olive_oil"], cookStory: ["你用菜刀剁开手臂，将橄榄油涂抹在蜜色的皮肤上，撒上黑胡椒粗粒；","你用铁签穿过肱二头肌，架在煤火上烤制，火焰舔舐着肌肉发达的手臂；","你不断翻转铁签，直到表皮呈现焦黄色，断面流出的汁液混着黑胡椒的辛辣味。","料理已完成！获得了\u201c骑士肌纹烤臂\u201d"] },
    cecilia_arm_dish: { id: "cecilia_arm_dish", name: "千金酒浸藕臂", type: "consumable", desc: "由塞西莉亚的手臂制作而成的酒浸藕臂，皮肤白嫩透明如瓷，散发着白葡萄酒的清香混合着少女肌肤淡淡的幽香。", effect: "agi", value: 2, ingredients: ["塞西莉亚的手臂","糖","白葡萄酒"], seasonings: ["sugar","white_wine"], cookStory: ["你提起那条纤细柔弱的手臂，皮肤白嫩如瓷能看到淡淡的蓝色血管；","你将手臂放入玻璃罐，倒入白葡萄酒淹没，加入冰糖；","你将罐子密封七日，酒液变成淡粉色，手臂皮肤呈现出透明的玉色。","料理已完成！获得了\u201c千金酒浸藕臂\u201d"] },
    isabella_arm_dish: { id: "isabella_arm_dish", name: "贵妇黄油烤臂", type: "consumable", desc: "由伊莎贝拉的手臂制作而成的黄油烤臂，表皮金黄油亮，散发着黄油的奶香混合着迷迭香的草本气息与烤熟的成熟女性肌肤特有的甜腻。", effect: "maxHp", value: 10, ingredients: ["伊莎贝拉的手臂","黄油","迷迭香","黑胡椒"], seasonings: ["butter","rosemary","black_pepper"], cookStory: ["你提起那条圆润丰满的手臂，用菜刀剁开；","你在手臂上涂抹融化的黄油，撒上黑胡椒和迷迭香；","你将伊莎贝拉的手臂架在铁架上烤制，直到表皮呈现金黄色。","料理已完成！获得了\u201c贵妇黄油烤臂\u201d"] },
    sophie_arm_dish: { id: "sophie_arm_dish", name: "女仆风干细臂", type: "consumable", desc: "由索菲的右臂制作而成的风干细臂，皮肤呈现出浅褐色紧绷如皮革，散发着黑胡椒的辛香混合着橄榄油的清香与风干肉特有的柴感。", effect: "def", value: 2, ingredients: ["索菲的手臂","黑胡椒","盐","橄榄油"], seasonings: ["black_pepper","salt","olive_oil"], cookStory: ["你提起那条纤细病态的手臂，用橄榄油涂抹，撒上粗盐和黑胡椒；","你将手臂悬挂在干燥通风处，让山风吹拂，皮肤逐渐失去水分变得紧绷；","风干二十日，直到皮肤紧绷如皮革，粉白色的肌肉纤维紧缩成细条。","料理已完成！获得了\u201c女仆风干细臂\u201d"] },
    elena_arm_dish: { id: "elena_arm_dish", name: "教师黄油煎臂", type: "consumable", desc: "由艾莲娜的手臂制作而成的黄油煎臂，表皮金黄微脆，散发着黄油的奶香混合着百里香的草本气息与海盐的咸鲜。", effect: "atk", value: 2, ingredients: ["艾莲娜的手臂","黄油","盐","百里香"], seasonings: ["butter","salt","thyme"], cookStory: ["你提起那条匀称冷白色的手臂，用菜刀剁成三段；","你用热锅融化黄油，放入手臂段，撒上海盐，煎至两面金黄；","你将煎至表皮微脆，断面流出的肉汁混着黄油的奶香。","料理已完成！获得了\u201c教师黄油煎臂\u201d"] },
    serena_arm_dish: { id: "serena_arm_dish", name: "瑟蕾娜手臂料理", type: "consumable", desc: "【占位符：瑟蕾娜手臂料理描述】", effect: "all", value: 3, ingredients: ["瑟蕾娜的手臂","【占位符：辅料1】","【占位符：辅料2】"], seasonings: ["ingredient_1","ingredient_2"], cookStory: ["【占位符：手臂料理烹饪剧情】"] },

    // ========== 手料理 ==========
    aisha_hand_dish: { id: "aisha_hand_dish", name: "监工茴香卤爪", type: "consumable", desc: "由艾莎的手制作而成的茴香卤爪，散发着矿井特有的粗犷与香料混合的气息。", effect: "agi", value: 1, ingredients: ["艾莎的手","八角","盐","水","桂皮"], seasonings: ["star_anise","salt","water","cinnamon"], cookStory: ["你把陶罐架在煤炉上，水开后放入八角桂皮，将断手五指张开插进卤汁；","你调至小火，慢卤一个半小时；","你关了火，让手在卤汁里浸泡了十分钟直到皮肤紧绷发亮。","料理已完成！获得了\u201c监工茴香卤爪\u201d"] },
    liana_hand_dish: { id: "liana_hand_dish", name: "骑士酱油卤爪", type: "consumable", desc: "由莉娅娜的手制作而成的酱油卤爪，亮红色的指甲油与深褐色的卤皮形成鲜明对比，散发着酱油的咸香混合着金属与女性手汗的独特气息。", effect: "atk", value: 1, ingredients: ["莉娅娜的手","月桂叶","酱油"], seasonings: ["bay_leaf","soy_sauce"], cookStory: ["你握住那只涂着亮红色指甲油的手，用刷子仔细刷洗指缝；","你将手放进卤锅，加入月桂叶和酱油，大火烧开后转小火慢卤；","你不断翻动那只手，让卤汁充分渗入断面的掌骨缝隙，直到皮肤变成深褐色。","料理已完成！获得了\u201c骑士酱油卤爪\u201d"] },
    cecilia_hand_dish: { id: "cecilia_hand_dish", name: "千金糖霜玉手", type: "consumable", desc: "由塞西莉亚的手制作而成的糖霜玉手，手指纤细如玉覆盖着洁白晶莹的糖霜脆壳，散发着焦糖与蛋清的甜香，整体像一件精致的易碎糖艺品。", effect: "agi", value: 1, ingredients: ["塞西莉亚的手","糖","鸡蛋"], seasonings: ["sugar","egg"], cookStory: ["你握住那只非常娇小细嫩的手，用软刷轻轻刷洗掌心；","你将手用铁钩悬挂起来，淋上打发的蛋清，再撒上白糖；","你将这只淋上糖液的小手低温烘烤，直到糖霜凝固成白色的脆壳。","料理已完成！获得了\u201c千金糖霜玉手\u201d"] },
    isabella_hand_dish: { id: "isabella_hand_dish", name: "贵妇蜜汁渍爪", type: "consumable", desc: "由伊莎贝拉的手制作而成的蜜汁渍爪，手爪呈透明的琥珀色，散发着蜂蜜的甜香混合着成熟女性手汗与自慰残留的淫靡气息。", effect: "maxHp", value: 5, ingredients: ["伊莎贝拉的手","蜂蜜"], seasonings: ["honey"], cookStory: ["你握住那对丰满柔软的手，深红色指甲油还完好无损；","你将这只断手浸入蜂蜜罐，让蜂蜜充分包裹每一根修长的手指；","你将罐子密封腌渍两日，让蜂蜜渗入断面的骨髓。","料理已完成！获得了\u201c贵妇蜜汁渍爪\u201d"] },
    sophie_hand_dish: { id: "sophie_hand_dish", name: "女仆盐渍冻爪", type: "consumable", desc: "由索菲的右手制作而成的盐渍冻爪，散发着清酒的米香混合着粗盐的咸鲜与姜片的辛辣气息。", effect: "def", value: 1, ingredients: ["索菲的手","清酒","盐","姜片"], seasonings: ["sake","salt","ginger"], cookStory: ["你握住那只布满劳作痕迹的手，用清酒冲洗；","你将索菲的断手浸入盐罐，倒入清酒淹没，放入姜片；","你将这只断手密封腌渍了十五日，手指蜷曲如鸡爪，透着清酒的米香。","料理已完成！获得了\u201c女仆盐渍冻爪\u201d"] },
    elena_hand_dish: { id: "elena_hand_dish", name: "教师花雕浸爪", type: "consumable", desc: "由艾莲娜的手制作而成的花雕浸爪，散发着花雕酒的醇香混合着姜片的温暖与冰糖的甜润。", effect: "atk", value: 1, ingredients: ["艾莲娜的手","花雕酒","姜片","糖"], seasonings: ["huadiao_wine","ginger","sugar"], cookStory: ["你握住那只修长骨节分明的手，将手放入瓷坛；","你倒入花雕酒淹没这只断手，加入姜片和冰糖，密封腌渍十五日；","启封时你拿出断手，手部皮肤呈现透明的玉色，透着温润的光泽。","料理已完成！获得了\u201c教师花雕浸爪\u201d"] },
    serena_hand_dish: { id: "serena_hand_dish", name: "瑟蕾娜手料理", type: "consumable", desc: "【占位符：瑟蕾娜手料理描述】", effect: "all", value: 2, ingredients: ["瑟蕾娜的手","【占位符：辅料1】","【占位符：辅料2】"], seasonings: ["ingredient_1","ingredient_2"], cookStory: ["【占位符：手料理烹饪剧情】"] },

    // ========== 脚料理 ==========
    aisha_foot_dish: { id: "aisha_foot_dish", name: "监工薄荷炖足", type: "consumable", desc: "由艾莎的脚制作而成的薄荷炖足，散发着清淡的腥甜与薄荷混合的气息。", effect: "agi", value: 2, ingredients: ["艾莎的脚","水","醋","薄荷"], seasonings: ["water","vinegar","mint"], cookStory: ["你慢慢脱下那只被血浸透成粉红色的棉袜，剥去脚趾缝里的血痂，将脚放进陶锅，加清水和野薄荷；","你用大火将水烧开，转小火炖半小时，之后用手指揉搓她的脚底；","最后，你淋上一圈醋，关火静置，让薄荷的凉气渗入皮肉。","料理已完成！获得了\u201c监工薄荷炖足\u201d"] },
    liana_foot_dish: { id: "liana_foot_dish", name: "骑士战靴蒸蹄", type: "consumable", desc: "由莉娅娜的脚制作而成的战靴蒸蹄，散发着生姜的辛辣、混合着浓烈肉香与皮革的气息。", effect: "agi", value: 3, ingredients: ["莉娅娜的脚","盐","姜片"], seasonings: ["salt","ginger"], cookStory: ["你脱下那只穿着金属战靴的脚，用粗盐搓洗脚底的厚茧；","你将断脚穿回战靴，放入蒸笼，铺上姜片，大火蒸四十分钟；","你打开蒸笼，将断脚从炙热的战靴中取出，生姜的辛辣混着脚汗味与肉味飘出。","料理已完成！获得了\u201c骑士战靴蒸蹄\u201d"] },
    cecilia_foot_dish: { id: "cecilia_foot_dish", name: "千金白丝蒸蹄", type: "consumable", desc: "由塞西莉亚的脚制作而成的白丝蒸蹄，白色厚丝袜湿润透明地包裹着小巧精致的脚掌，散发着桂花的清香混合着皮革与少女脚汗的淡淡气息。", effect: "agi", value: 2, ingredients: ["塞西莉亚的脚","桂花"], seasonings: ["osmanthus"], cookStory: ["你脱下那只黑色小皮鞋，将脚连同丝袜一起放入蒸笼，撒上干桂花；","大火蒸制三十分钟，蒸汽中白色厚丝袜变得湿润透明；","你蒸至丝袜与皮肤粘连，黑色小皮鞋放在一旁作为点缀。","料理已完成！获得了\u201c千金白丝蒸蹄\u201d"] },
    isabella_foot_dish: { id: "isabella_foot_dish", name: "贵妇黑丝焙蹄", type: "consumable", desc: "由伊莎贝拉的脚制作而成的高跟焙蹄，散发着芝士的甜香混合着皮革、黑色丝袜与成熟女性脚汗与肉香的淫靡气息。", effect: "maxHp", value: 8, ingredients: ["伊莎贝拉的脚","芝士"], seasonings: ["cheese"], cookStory: ["你脱下那只黑色高跟鞋，将脚连同丝袜一起放入烘箱；","你在高跟鞋中撒入芝士碎，再将煮熟的肉脚穿入，大火烘焙四十分钟；","你将鞋与黑丝肉脚一同拿出冷却。","料理已完成！获得了\u201c贵妇黑丝焙蹄\u201d"] },
    sophie_foot_dish: { id: "sophie_foot_dish", name: "女仆清酒浸蹄", type: "consumable", desc: "由索菲的脚制作而成的清酒浸蹄，散发着清酒的米香混合着昆布的鲜甜与姜片的温暖。", effect: "def", value: 1, ingredients: ["索菲的脚","清酒","昆布","姜片"], seasonings: ["sake","kelp","ginger"], cookStory: ["你脱下那只不合脚的硬皮鞋，将脚放入陶罐；","你倒入清酒淹没索菲的断足，放入昆布和姜片，密封浸泡十日；","十日后你将断脚取出时，皮肤呈现透明的玉色。","料理已完成！获得了\u201c女仆清酒浸蹄\u201d"] },
    elena_foot_dish: { id: "elena_foot_dish", name: "教师柠檬香煎蹄", type: "consumable", desc: "由艾莲娜的脚制作而成的柠檬香煎蹄，表皮金黄酥脆，散发着黄油的奶香混合着柠檬汁的酸爽与欧芹的清香。", effect: "agi", value: 2, ingredients: ["艾莲娜的脚","黄油","柠檬汁","欧芹碎"], seasonings: ["butter","lemon_juice","parsley"], cookStory: ["你提起那只冷白色的脚，用黄油涂抹整个脚部；","你将脚放入热锅，煎至表皮金黄酥脆，倒入柠檬汁，撒上欧芹碎；","你将煎好的脚摆盘，脚趾微微蜷曲，散发着诱人的香气。","料理已完成！获得了\u201c教师柠檬香煎蹄\u201d"] },
    elena_leg_dish: { id: "elena_leg_dish", name: "教师香煎腿排", type: "consumable", desc: "由艾莲娜的右腿制作而成的香煎腿排，表皮金黄酥脆，散发着十足的肉香、橄榄油的清香混合着黑胡椒的辛香。", effect: "atk", value: 3, ingredients: ["艾莲娜的腿","橄榄油","黑胡椒"], seasonings: ["olive_oil","black_pepper"], cookStory: ["你将那条修长笔直的冷白色大腿平放，用菜刀切成厚片；","你在热锅内倒入橄榄油，放入腿排，撒上黑胡椒，煎至两面金黄；","你将腿排煎至表皮酥脆，肉质松软，油脂渗入皮肤之中。","料理已完成！获得了\u201c教师香煎腿排\u201d"] },
    serena_foot_dish: { id: "serena_foot_dish", name: "瑟蕾娜脚料理", type: "consumable", desc: "【占位符：瑟蕾娜脚料理描述】", effect: "all", value: 3, ingredients: ["瑟蕾娜的脚","【占位符：辅料1】","【占位符：辅料2】"], seasonings: ["ingredient_1","ingredient_2"], cookStory: ["【占位符：脚料理烹饪剧情】"] },

    // ========== 乳房料理 ==========
    aisha_breast_dish: { id: "aisha_breast_dish", name: "监工野果煎乳", type: "consumable", desc: "由艾莎的乳房制作而成的野果煎乳，两面金黄，散发着奶腥味混着焦香，旁边配着野山椒粉末。", effect: "maxHp", value: 15, ingredients: ["艾莎的乳房","盐","野山椒"], seasonings: ["salt","wild_pepper"], cookStory: ["你将铁锅烧到冒烟，用刀尖挑开断面的脂肪层；","你将艾莎的乳房扔进油锅中，慢慢煎，乳头逐渐煎成深褐色；","你将乳房翻面，撒上捏碎的野山椒末，再煎三分钟。","料理已完成！获得了\u201c监工野果煎乳\u201d"] },
    liana_breast_dish: { id: "liana_breast_dish", name: "骑士奶冻", type: "consumable", desc: "由莉娅娜的乳房与乳汁制作而成的骑士奶冻，奶冻呈半透明的乳白色，散发着蜂蜜的甜香混合着乳汁的腥甜与女性体味。", effect: "atk", value: 2, ingredients: ["莉娅娜的乳房","莉娅娜的鲜奶","蜂蜜","吉利丁片"], seasonings: ["liana_milk","honey","gelatin_sheet"], cookStory: ["你挤压那只C杯乳房，用力挤出残存的乳汁；","你倒出一瓶莉娅娜的乳汁，将其加热，加入泡软的吉利丁片和蜂蜜，将那只乳房断面朝下浸入奶冻液中；","你将奶冻冷藏凝固后取出，乳房淹没其中。","料理已完成！获得了\u201c骑士奶冻\u201d"] },
    cecilia_breast_dish: { id: "cecilia_breast_dish", name: "千金樱桃奶冻", type: "consumable", desc: "由塞西莉亚的乳房与乳汁制作而成的樱桃奶冻，散发着樱桃的甜香混合着处女乳汁的腥甜与少女体香。", effect: "agi", value: 2, ingredients: ["塞西莉亚的乳房","塞西莉亚的奶","吉利丁片","樱桃"], seasonings: ["cecilia_milk","gelatin_sheet","cherry"], cookStory: ["你挤压那只非常娇小的A罩杯乳房，用力挤出残存的处女乳汁；","你将乳汁加热，加入泡软的吉利丁和樱桃糖浆，将那只娇小乳房断面朝下浸入奶冻液中；","你将奶冻与乳房冷藏凝固，奶冻呈透明的粉红色。","料理已完成！获得了\u201c千金樱桃奶冻\u201d"] },
    isabella_breast_dish: { id: "isabella_breast_dish", name: "贵妇乳汁炖乳", type: "consumable", desc: "由伊莎贝拉的乳房与乳汁制作而成的乳汁炖乳，散发着红枣的甜香混合着成熟女性乳汁的腥甜与体香。", effect: "maxHp", value: 20, ingredients: ["伊莎贝拉的乳房","伊莎贝拉的奶","糖","红枣"], seasonings: ["isabella_milk","sugar","red_date"], cookStory: ["你挤压那只饱满挺拔的D罩杯乳房，用力挤出大量乳汁；","你将伊莎贝拉的乳汁倒入砂锅，加入红枣和冰糖，放入那只乳房，大火烧开后转小火慢炖；","你炖煮了四十分钟，乳汁变得浓稠。","料理已完成！获得了\u201c贵妇乳汁炖乳\u201d"] },
    sophie_breast_dish: { id: "sophie_breast_dish", name: "女仆蜜渍薄乳", type: "consumable", desc: "由索菲的乳房制作而成的蜜渍薄乳，散发着蜂蜜的甜香混合着桂花的清香。", effect: "def", value: 2, ingredients: ["索菲的乳房","蜂蜜","桂花"], seasonings: ["honey","osmanthus"], cookStory: ["你挤压那只单薄的A杯乳房想排出所有乳汁，却发现这只乳房实在贫瘠得一无所有；","你将乳房浸入蜜罐，用蜂蜜完全覆盖，撒上干桂花；","你将索菲的乳房密封蜜渍二十日，直到乳房扁平如薄片。","料理已完成！获得了\u201c女仆蜜渍薄乳\u201d"] },
    elena_breast_dish: { id: "elena_breast_dish", name: "教师清酒冰酪", type: "consumable", desc: "由艾莲娜的乳房制作而成的清酒冰酪，散发着清酒的米香混合着冰糖的甜润与乳房的脂肪气息。", effect: "atk", value: 3, ingredients: ["艾莲娜的乳房","艾莲娜的奶","清酒","糖","吉利丁片"], seasonings: ["elena_milk","sake","sugar","gelatin_sheet"], cookStory: ["你挤压那只挺拔丰满的C罩杯乳房，用力挤出剩余的乳汁；","你将清酒加热，加入冰糖和泡软的吉利丁，放入那只乳房；","你将冰酪冷藏凝固，乳房半埋在透明的冰酪中，如同冷月下的玉雕。","料理已完成！获得了\u201c教师清酒冰酪\u201d"] },
    serena_breast_dish: { id: "serena_breast_dish", name: "瑟蕾娜乳料理", type: "consumable", desc: "【占位符：瑟蕾娜乳房料理描述】", effect: "all", value: 5, ingredients: ["瑟蕾娜的乳房","【占位符：辅料1】","【占位符：辅料2】"], seasonings: ["ingredient_1","ingredient_2"], cookStory: ["【占位符：乳房料理烹饪剧情】"] }
});